version: "3.8"
services:
  wg-easy:
    image: wg-easy
    command: npm run serve
    volumes:
      - ./src/:/app/server
      - ./webui/dist:/app/www
    environment:
      # - PASSWORD=p
      - WG_HOST=192.168.1.233
